# Generated by Django 2.2.24 on 2022-12-12 09:25

from django.db import migrations


def define_field_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    year_marker = 2015
    for flat in Flat.objects.all():
        if flat.construction_year >= year_marker:
            flat.new_building = True
        else:
            flat.new_building = False
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(define_field_new_building),
    ]
