# Generated by Django 2.2.24 on 2022-12-14 10:57

from django.db import migrations

def Add_apparts_owner_records(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Apparts_owner = apps.get_model('property', 'Apparts_owner')
    for flat in Flat.objects.iterator():
        apparts_owner_records,*_ = Apparts_owner.objects.get_or_create(
            name=flat.owner,
            phone_number=flat.owners_phonenumber,
            pure_phone=flat.owner_pure_phone,
            )
        apparts_owner_records.flats.add(flat)
        apparts_owner_records.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_apparts_owner'),
    ]

    operations = [
        migrations.RunPython(Add_apparts_owner_records)
    ]
