# Generated by Django 2.2.24 on 2022-12-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20221214_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.AddField(
            model_name='flat',
            name='owners',
            field=models.ManyToManyField(to='property.Apparts_owner', verbose_name='Собственники'),
        ),
    ]
