# Generated by Django 2.2.24 on 2022-12-14 21:27

from django.db import migrations

def add_owners_to_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Apparts_owner = apps.get_model('property', 'Apparts_owner')
    for flat in Flat.objects.iterator():
        flat_owners = Apparts_owner.objects.filter(flats=flat)
        for owner in flat_owners:
            flat.owners.add(owner)
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20221215_0025'),
    ]

    operations = [
        migrations.RunPython(add_owners_to_flats)
    ]
